export const ADMIN_LIST_USER_REQUEST = "ADMIN_LIST_USER_REQUEST";
export const ADMIN_LIST_USER_SUCCESS = "ADMIN_LIST_USER_SUCCESS";
export const ADMIN_LIST_USER_FAIL = "ADMIN_LIST_USER_FAIL";

export const ADMIN_DELETE_PRODUCT_REQUEST = "ADMIN_DELETE_PRODUCT_REQUEST";
export const ADMIN_DELETE_PRODUCT_SUCCESS = "ADMIN_DELETE_PRODUCT_SUCCESS";
export const ADMIN_DELETE_PRODUCT_FAIL = "ADMIN_DELETE_PRODUCT_FAIL";

export const ADMIN_CREATE_NEW_PRODUCT_REQUEST =
  "ADMIN_CREATE_NEW_PRODUCT_REQUEST";
export const ADMIN_CREATE_NEW_PRODUCT_SUCCESS =
  "ADMIN_CREATE_NEW_PRODUCT_SUCCESS";
export const ADMIN_CREATE_NEW_PRODUCT_FAIL = "ADMIN_CREATE_NEW_PRODUCT_FAIL";

export const ADMIN_CREATE_NEW_PRODUCT_RESET = "ADMIN_CREATE_NEW_PRODUCT_RESET";

export const ADMIN_UPDATE_PRODUCT_REQUEST = "ADMIN_UPDATE_PRODUCT_REQUEST";
export const ADMIN_UPDATE_PRODUCT_SUCCESS = "ADMIN_UPDATE_PRODUCT_SUCCESS";
export const ADMIN_UPDATE_PRODUCT_FAIL = "ADMIN_UPDATE_PRODUCT_FAIL";

export const ADMIN_UPDATE_PRODUCT_RESET = "ADMIN_UPDATE_PRODUCT_RESET";
