export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const CART_CLEAR_ITEMS = "CART_CLEAR_ITEMS";

export const ADMIN_LIST_ORDER_REQUEST = "ADMIN_LIST_ORDER_REQUEST";
export const ADMIN_LIST_ORDER_SUCCESS = "ADMIN_LIST_ORDER_SUCCESS";
export const ADMIN_LIST_ORDER_FAIL = "ADMIN_LIST_ORDER_FAIL";

export const USER_GET_ORDER = "USER_GET_ORDER";
export const LOADING = "LOADING";
export const ORDER_DETAILS_FAIL = "ORDER_DETAILS_FAIL";

export const USER_GET_MY_ORDER = "USER_GET_MY_ORDER";

export const ORDER_PAY_REQUEST = "ORDER_PAY_REQUEST";
export const ORDER_PAY_SUCCESS = "ORDER_PAY_SUCCESS";
export const ORDER_PAY_FAIL = "ORDER_PAY_FAIL";
export const ORDER_PAY_RESET = "ORDER_PAY_RESET";

export const REMOVE_ADDRESS = "REMOVE_ADDRESS";

export const ORDER_DELIVER_REQUEST = "ORDER_DELIVER_REQUEST";
export const ORDER_DELIVER_SUCCESS = "ORDER_DELIVER_SUCCESS";
export const ORDER_DELIVER_FAIL = "ORDER_DELIVER_FAIL";
export const ORDER_DELIVER_RESET = "ORDER_DELIVER_RESET";
