# Generated by Django 3.2.7 on 2021-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='postal_Code',
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shipping_Price',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default='./default.png', null=True, upload_to=''),
        ),
    ]
